// scripts/pdf_to_images.js
const fs = require("fs");
const path = require("path");
const { execSync } = require("child_process");

const INPUT = path.join(__dirname, "..", "public", "samples", "sample-kyoto-standard.pdf");
const OUT_DIR = path.join(__dirname, "..", "public", "samples", "pages");
const COUNT_TS = path.join(__dirname, "..", "lib", "sample_pages_count.ts");

function main() {
  if (!fs.existsSync(INPUT)) {
    console.error(`[pdf_to_images] Input PDF not found: ${INPUT}`);
    process.exit(1);
  }

  fs.rmSync(OUT_DIR, { recursive: true, force: true });
  fs.mkdirSync(OUT_DIR, { recursive: true });

  console.log("[pdf_to_images] converting...");
  const prefix = path.join(OUT_DIR, "page");
  execSync(`pdftoppm -png -r 144 "${INPUT}" "${prefix}"`, { stdio: "inherit" });

  // pdftoppm outputs page-1.png, page-2.png, ... — rename to page-01.png, page-02.png, ...
  const files = fs.readdirSync(OUT_DIR)
    .filter((f) => f.endsWith(".png"))
    .sort();

  for (let i = 0; i < files.length; i++) {
    const num = String(i + 1).padStart(2, "0");
    const newName = `page-${num}.png`;
    if (files[i] !== newName) {
      fs.renameSync(path.join(OUT_DIR, files[i]), path.join(OUT_DIR, newName));
    }
    const kb = Math.round(fs.statSync(path.join(OUT_DIR, newName)).size / 1024);
    console.log(`  ${newName} (${kb}KB)`);
  }

  fs.writeFileSync(
    COUNT_TS,
    `// Auto-generated by scripts/pdf_to_images.js — do not edit manually.\nexport const SAMPLE_PAGES_COUNT = ${files.length};\n`
  );

  console.log(`\n✅ ${files.length} pages → public/samples/pages/`);
  console.log(`✅ lib/sample_pages_count.ts updated`);
}

main();
